//   default package
// Generated Feb 4, 2021 6:32:54 PM by Hibernate Tools 5.2.12.Final

package SBHibernateIntegrate.SBHibernateIntegrater.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "springhb")
public class Employee implements java.io.Serializable {

	private Integer id;
	private String ename;
	private String contactno;
	private String department;
	private String status;

	public Employee() {
	}

	public Employee(String ename, String contactno, String department, String status) {
		this.ename = ename;
		this.contactno = contactno;
		this.department = department;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ename", nullable = false, length = 45)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "contactno", nullable = false, length = 45)
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	@Column(name = "department", nullable = false, length = 45)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
